language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - composer self-update
  - composer --prefer-source install

notifications:
  email: false

addons:
  code_climate:
    repo_token:: 3f96e0739f5ada6c5e2aedb71278a9b1ba2db06dc139426ae8d657b0f3020308

after_script:
      - vendor/bin/test-reporter